#!/bin/bash

###################################################
#
#	-Bash script to correct the direction the 
#	 motor moves per command
#
###################################################

if [[ "`cat /home/pi/SmartCurtain/init.py`" == *"state == 'C'"* ]]; then
	sed -i -e "s/state == 'C'/state == 'O'/g" /home/pi/SmartCurtain/init.py
else
	sed -i -e "s/state == 'O'/state == 'C'/g" /home/pi/SmartCurtain/init.py
fi

echo -e '\033[0;42mSuccessfully changed motor direction\033[0;49m'

# created by: MPZinke on 01.19.19