#!/bin/bash

###################################################
#
#	-Bash script to edit feed.py & init.py from
#	 terminal
#	-Creates/replaces AIOkey, U-name, Feed-names
#	 and travel distance of curtain
#
###################################################

read -p "Adafruit IO will be set up.  To do this, you will need to 
have alredy set up an account and feeds.  For more information plese
check the documentation.  You will need an AIO Key, User Name, 
Open Key, Close Key and Distance [in] your curtain moves.
Continue? (Y/N): " continue
if [ "$continue" == 'Y' ]
then
	read -p "Please enter your Adafruit IO key: " aio_key
	read -p "Please enter your Adafruit User Name: " u_name
	read -p "Please enter your Open Key: " open_key
	read -p "Please enter your Close Key: " close_key
	read -p "Please enter the distance [in] the curtain moves: " distance
	read -p "	AIO Key: $aio_key
	User Name: $u_name
	Open Key: $open_key
	Close Key: $close_key
	Distance: $distance
Is all information correct?(Y/N): " validate
	if [ "$validate" == Y ] 
	then
		old_key=$(cut -d "=" -f 2 <<< $(grep -F "self.key =" /home/pi/SmartCurtain/feed.py))
		old_name=$(cut -d "=" -f 2 <<< $(grep -F "self.name =" /home/pi/SmartCurtain/feed.py))
		old_open=$(cut -d "=" -f 2 <<< $(grep -F "openkey=" /home/pi/SmartCurtain/feed.py))
		old_close=$(cut -d "=" -f 2 <<< $(grep -F "closekey=" /home/pi/SmartCurtain/feed.py))
		old_dist=$(grep -F "distance =" /home/pi/SmartCurtain/init.py)

		sed -i -e "s/$old_key/ '$aio_key'/g" /home/pi/SmartCurtain/feed.py
		sed -i -e "s/$old_name/ '$u_name'/g" /home/pi/SmartCurtain/feed.py
		sed -i -e "s/$old_open/$open_key/g" /home/pi/SmartCurtain/feed.py
		sed -i -e "s/$old_close/$close_key/g" /home/pi/SmartCurtain/feed.py
		sed -i -e "s/$old_dist/	distance = $distance/g" /home/pi/SmartCurtain/init.py
		echo 'Info updated'
	fi
else
	echo -e '\033[0;43mYou have elected to not update your Adafruit client information.
If you would like to in the future enter "bash ~/SmartCurtain/AIOSetup" \033[0;49m'
fi

# created by: MPZinke on 01.19.19